# Generated by Django 4.2.6 on 2024-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentowner',
            options={},
        ),
    ]
