# Generated by Django 4.2.6 on 2024-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_apartmentowner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentowner',
            options={'verbose_name': 'Владелец квртиры', 'verbose_name_plural': 'Владельцы квартиры'},
        ),
        migrations.AlterField(
            model_name='apartmentowner',
            name='ownerBorn',
            field=models.DateTimeField(verbose_name='Дата рождения владельца'),
        ),
        migrations.AlterField(
            model_name='family',
            name='checkDate',
            field=models.DateTimeField(verbose_name='дата проверки'),
        ),
    ]
